{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "gh-ost.fullname" . }}
  labels:
    {{- include "gh-ost.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable | default 1 }}
  selector:
    matchLabels:
      {{- include "gh-ost.selectorLabels" . | nindent 6 }}
{{- end }}
