{{- if .Values.secret.mycnf }}
apiVersion: v1
kind: Secret
metadata:
  name: gh-ost-secret
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name | quote }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  my.cnf: {{ .Values.secret.mycnf | b64enc }}
{{- end }}
