apiVersion: v1
kind: Service
metadata:
  name: {{ include "gh-ost.fullname" . }}
  labels:
    {{- include "gh-ost.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3306
      protocol: TCP
      name: mysql
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "gh-ost.selectorLabels" . | nindent 4 }}
